import { router, protectedProcedure, publicProcedure } from "../_core/trpc";

const unavailable = () => ({
  unavailable: true,
  error: "This v1 compatibility endpoint is unavailable until backed by a verified implementation",
});

export const phase32Router = router({
  v1GetDashboard: protectedProcedure.query(async () => unavailable()),
  v1GetUserProfile: protectedProcedure.query(async () => unavailable()),
  v1GetWallet: protectedProcedure.query(async () => unavailable()),
  v1GetPortfolio: protectedProcedure.query(async () => unavailable()),
  v1GetTransactions: protectedProcedure.query(async () => unavailable()),
  v1GetLeaderboard: publicProcedure.query(async () => unavailable()),
  v1GetAchievements: protectedProcedure.query(async () => unavailable()),
  v1GetNotifications: protectedProcedure.query(async () => unavailable()),
  v1GetMessages: protectedProcedure.query(async () => unavailable()),
  v1GetFeed: publicProcedure.query(async () => unavailable()),
  v1CreatePost: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1UpdateProfile: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1SendMessage: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1FollowUser: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1UnfollowUser: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1LikePost: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1CommentPost: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1SharePost: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1DeletePost: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1ReportPost: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1GetCourses: publicProcedure.query(async () => unavailable()),
  v1EnrollCourse: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1CompleteCourse: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1GetCertificates: protectedProcedure.query(async () => unavailable()),
  v1PlayGame: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1GetGameScores: protectedProcedure.query(async () => unavailable()),
  v1BuyItem: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1SellItem: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1GetMarketplace: publicProcedure.query(async () => unavailable()),
  v1SearchProducts: publicProcedure.query(async () => unavailable()),
  v1GetProductDetails: publicProcedure.query(async () => unavailable()),
  v1AddToCart: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1RemoveFromCart: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1Checkout: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1TradeToken: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1SwapCrypto: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1StakeCrypto: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1UnstakeCrypto: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1GetStakingRewards: protectedProcedure.query(async () => unavailable()),
  v1VoteProposal: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1CreateProposal: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1GetProposals: publicProcedure.query(async () => unavailable()),
  v1GetGovernanceStats: publicProcedure.query(async () => unavailable()),
  v1JoinCommunity: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1LeaveCommunity: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1GetCommunities: publicProcedure.query(async () => unavailable()),
  v1PostInCommunity: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
  v1GetCommunityPosts: publicProcedure.query(async () => unavailable()),
  v1ModerateCommunity: protectedProcedure.mutation(async () => ({ success: false, ...unavailable() })),
});
